### ISSUE TITLE
Works on OSX!

### ISSUE THREAD

**Issue by rvt** [Spasi/LWJGL-FX#1]
Just wanted to leave a note here that this works on OSX since somebody on the java-gaming closed the thread for no reason. (http://www.java-gaming.org/topics/lwjgl-javafx-integration/27801/view.html)

All you have to do is add this to your main:

```
    System.setProperty("javafx.macosx.embedded", "true");
    java.awt.Toolkit.getDefaultToolkit();
```

(properly you want to detect OSX).
With your demo I got 250 frames/sec

**Comment by Spasi** [comment]
Thanks!

Could you possibly also try it on JDK 8? I think javafx.macosx.embedded is not required anymore with JavaFX 8.

**Comment by rvt** [comment]
hello!

I will try tomorrow and see if my app works with java 8.
Out of curiosity, have you ever created and destroyed the OpenGL Context? (I hope I have the terminology right).

What I currently experience is this:
My application requires a pop-up window to display some 3D info.
So I abstracted away some classes so I can easily re-created the OpenGL context and kick off a new thread whena a new dialog opens.
The problem is that when the dialog closes and the OpenGL thread stops (LWJGL Renderer), the thread isn’t removed from memory.

I verified that my controller classes and the OpenGL Image (you have named it gearsView) is removed (javafx always seems to want to have one ‘dirty’ hanging around though) 
from memory. it’s just seems like that the the thread hangs around.
However, I also find that fast_patch_cache keeps having a reference around :

or… is there something I forget to cleanup? 

I do call:

```
    renderStream.destroy();
    pbuffer.destroy()
```

## 

Kind Regards,

e:ries@vantwisk.nl / Tel. +1 803 426 3350 / Skype: r.vantwisk
http://riesvantwisk.com / chat:vantwisk@gmail.com

**Comment by Spasi** [comment]
I'm not aware of any leaks in LWJGL, the pbuffer.destroy() call should be cleaning everything up nicely. It would be great if you could write a simple demo that reproduces the issue though, just to make sure it's not related to LWJGL internals.

**Comment by rvt** [comment]
Hey Spasi (is that your name??),

attached a version of your demo application that open’s a new scene with a OpenGL gears renderer.
I have verified that even after GC (forced using yourkit, but even after extended periods of time) 
the thread would be kept in memory.

Today I will spend a bit of time to see if I can isolate it, but after I looked at it on my own app yesterday for
some time I couldn’t isolate it yet.

## 

Kind Regards,

e:ries@vantwisk.nl / Tel. +1 803 426 3350 / Skype: r.vantwisk
http://riesvantwisk.com / chat:vantwisk@gmail.com

**Comment by rvt** [comment]
Hey 

As promised, but a bit later due to my time constrains I have tested it on OSX.
I still need 'java.awt.Toolkit.getDefaultToolkit();’ in java 8 but System.setProperty("javafx.macosx.embedded", "true”); isn’t required
anymore.

a couple of day’s ago I started to release the code on github and can be found here : https://github.com/rvt/cnctools

Rendering using OpenGL is relative stable, but I do sometime have some issues where rendering stops,
usually when I play around in my debugger so It’s not a real concern.

cnctools is a tool for generating and viewing g-code used in the machine industry, and my little learning
code for learning javafx.

## 

Kind Regards,

e:ries@vantwisk.nl / Tel. +1 803 426 3350 / Skype: r.vantwisk
http://riesvantwisk.com / chat:vantwisk@gmail.com
