### ISSUE TITLE
Same thing for AWT/Swing

### ISSUE THREAD

**Issue by piegamesde** [Spasi/LWJGL-FX#11]
Inspired by this project, I built a simple class that does the same thing, just for AWT (Canvas) and Swing (JPanel). It is just a simple component that paints a cached image. That image is taken from an OpenGL texture attached to an FBO for off screen rendering.

Does this belong into this project or should I upload it on a separate GitHub repo?

**Comment by Spasi** [comment]
Better make a separate repo. I don't want to give the impression that this approach is somehow viable, now that a [much better alternative](https://bitbucket.org/cuchaz/jfxgl) exists.

**Comment by piegamesde** [comment]
I tried that "much better alternative" and it didn't really work well for me because it's still quite buggy and JavaFX hasn't made a good first impression on me either.

**Comment by piegamesde** [comment]
So, here's my little ugly beast: (https://github.com/piegamesde/SwingGL). Please have a look at it and tell me what you think about it.
