### ISSUE TITLE
JavaFX + OpenGL + Virtual Box

### ISSUE THREAD

**Issue by rvt** [Spasi/LWJGL-FX#2]
Ooo goodies,

I have been researching this quite a bit but this seems to be an issue.
As far as my research goes is that puffers are not supported by Virtual Box, or even vmware or parallels...

Is there a way to by-pass puffers usage using a different rendering technique?

**Comment by Spasi** [comment]
Yes, you can use a hidden window, but I'm afraid that's not possible with LWJGL 2.x. It is of course supported in LWJGL 3, but that's nowhere near production ready.
