### ISSUE TITLE
Cannot change "MSAA Samples" in the application

### ISSUE THREAD

**Issue by lxjuly** [Spasi/LWJGL-FX#7]
I am still trying to learn and understand the code. As I change the "MSAA Samples" by drag the slider the "Gears" window becomes completely black and one error keeps being thrown, basically the application only works when "MSAA Samples" is set to 1.

My system runs **jdk 8 (update 5), javafx and OpenGL 3.3 with jwjgl 2.9.1**

```
[LWJGL] ARB_debug_output message
    ID: 1286
    Source: API
    Type: ERROR
    Severity: HIGH
    Message: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.
```

**Comment by jiping-s** [comment]
MSAA changing fails only when the initial MSAA samples is 1/none. If you set the default to any other value, changing would work fine.

**Comment by lxjuly** [comment]
I see. Thanks!

**Comment by Spasi** [comment]
I'm afraid I cannot reproduce this bug. On what GPU and OS does it happen?

**Comment by lxjuly** [comment]
GPU is nVidia Qudro FX4600, driver 333.11. OS is Windows 7 64bit SP1

**Comment by jiping-s** [comment]
GPU nVIDIA GTX860M, driver 340.66 (quardo driver), Windows Server 2012
GPU AMD Radeon 7770, driver 14.4, Windows Server 2012
